// EN/ES strings for the Equipment Check tablet app. Language follows the
// device (useTeamHubLang, shared with Team Hub) with the same flag toggle.
import type { TeamHubLang } from "@/app/team-hub/teamHubStrings";

export const EQUIPMENT_CHECK_STRINGS = {
  en: {
    title: "Equipment Check",
    loading: "Loading…",
    noSignal: "No signal — try again",
    somethingWrong: "Something went wrong. Try again.",
    linkNotActive: "This link isn't active anymore. Ask your office for the new one.",
    back: "Back",
    cancel: "Cancel",
    whoAreYou: "Who are you?",
    newBadge: "New",
    noPeople: "No one is set up yet. Ask your office.",
    enterPin: "Enter your PIN",
    notYou: "Not you?",
    wrongPin: "Wrong PIN — try again",
    lockedOut: "Too many tries. Wait 15 minutes or ask your office.",
    createPin: "Create your PIN",
    createPinHint: "Pick 4 numbers you'll remember",
    confirmPin: "Enter it again",
    pinMismatch: "Didn't match — try again",
    setupClosed: "PIN setup isn't open. Ask your office.",
    signedOut: "Signed out. Start again.",
    whatDidYouUse: "What did you use?",
    noEquipment: "No equipment yet.",
    howDidYouLeaveIt: "How did you leave it?",
    good: "Good",
    damaged: "Damaged or not working",
    lost: "Lost",
    takePicture: "TAKE PICTURE",
    photoRequired: "Take at least 1 picture",
    photoCount: (n: number) => `${n}/3 pictures`,
    photoTooBig: "That picture is too big (8MB max).",
    notesPlaceholder: "Notas / Comentarios",
    send: "SEND",
    sending: "Sending…",
    done: "Done! Thank you",
  },
  es: {
    title: "Revisión de equipo",
    loading: "Cargando…",
    noSignal: "Sin señal — intenta otra vez",
    somethingWrong: "Algo salió mal. Intenta otra vez.",
    linkNotActive: "Este enlace ya no está activo. Pide el nuevo en tu oficina.",
    back: "Atrás",
    cancel: "Cancelar",
    whoAreYou: "¿Quién eres?",
    newBadge: "Nuevo",
    noPeople: "Nadie está configurado todavía. Pregunta en tu oficina.",
    enterPin: "Escribe tu PIN",
    notYou: "¿No eres tú?",
    wrongPin: "PIN incorrecto — intenta otra vez",
    lockedOut: "Demasiados intentos. Espera 15 minutos o pregunta en tu oficina.",
    createPin: "Crea tu PIN",
    createPinHint: "Escoge 4 números que vas a recordar",
    confirmPin: "Escríbelo otra vez",
    pinMismatch: "No coincide — intenta otra vez",
    setupClosed: "La creación de PIN no está abierta. Pregunta en tu oficina.",
    signedOut: "Sesión cerrada. Empieza otra vez.",
    whatDidYouUse: "¿Qué usaste?",
    noEquipment: "No hay equipo todavía.",
    howDidYouLeaveIt: "¿Cómo lo dejaste?",
    good: "Bien",
    damaged: "Dañado o no funciona",
    lost: "Perdido",
    takePicture: "TOMAR FOTO",
    photoRequired: "Toma al menos 1 foto",
    photoCount: (n: number) => `${n}/3 fotos`,
    photoTooBig: "Esa foto es muy grande (máximo 8MB).",
    notesPlaceholder: "Notas / Comentarios",
    send: "ENVIAR",
    sending: "Enviando…",
    done: "¡Listo! Gracias",
  },
} as const;

export function equipmentCheckStrings(lang: TeamHubLang) {
  return EQUIPMENT_CHECK_STRINGS[lang];
}
