// EN/ES strings for the Equipment Check tablet app. Language follows the
// device (useTeamHubLang, shared with Team Hub) with the same flag toggle.
import type { TeamHubLang } from "@/app/team-hub/teamHubStrings";

export const EQUIPMENT_CHECK_STRINGS = {
  en: {
    title: "Equipment Check",
    loading: "Loading…",
    noSignal: "No signal — try again",
    somethingWrong: "Something went wrong. Try again.",
    linkNotActive: "This link isn't active anymore. Ask your office for the new one.",
    back: "Back",
    home: "Home",
    cancel: "Cancel",
    whoAreYou: "Who are you?",
    newBadge: "New",
    noPeople: "No one is set up yet. Ask your office.",
    enterPin: "Enter your PIN",
    notYou: "Not you?",
    wrongPin: "Wrong PIN — try again",
    lockedOut: "Too many tries. Wait 15 minutes or ask your office.",
    createPin: "Create your PIN",
    createPinHint: "Pick 4 numbers you'll remember",
    confirmPin: "Enter it again",
    pinMismatch: "Didn't match — try again",
    setupClosed: "PIN setup isn't open. Ask your office.",
    signedOut: "Signed out. Start again.",
    whatDidYouUse: "What did you use?",
    noEquipment: "No equipment yet.",
    howDidYouLeaveIt: "How did you leave it?",
    good: "Good",
    damaged: "Damaged or not working",
    lost: "Lost",
    takePicture: "TAKE PICTURE",
    photoRequired: "Take at least 1 picture",
    photoCount: (n: number) => `${n}/3 pictures`,
    photoTooBig: "That picture is too big (8MB max).",
    notesPlaceholder: "Notas / Comentarios",
    send: "SEND",
    sending: "Sending…",
    done: "Done! Thank you",
    vehicle: "Vehicle",
    mileageQuestion: "Mileage?",
    mileageHint: "The number on the dashboard",
    next: "NEXT",
    lastMileage: (n: string) => `Last time: ${n}`,
    lowerCheck: (last: string) => `Are you sure? Last reading was ${last}`,
    yesRight: "Yes, it's right",
    fixIt: "Fix it",
  },
  es: {
    title: "Revisión de equipo",
    loading: "Cargando…",
    noSignal: "Sin señal — intenta otra vez",
    somethingWrong: "Algo salió mal. Intenta otra vez.",
    linkNotActive: "Este enlace ya no está activo. Pide el nuevo en tu oficina.",
    back: "Atrás",
    home: "Inicio",
    cancel: "Cancelar",
    whoAreYou: "¿Quién eres?",
    newBadge: "Nuevo",
    noPeople: "Nadie está configurado todavía. Pregunta en tu oficina.",
    enterPin: "Escribe tu PIN",
    notYou: "¿No eres tú?",
    wrongPin: "PIN incorrecto — intenta otra vez",
    lockedOut: "Demasiados intentos. Espera 15 minutos o pregunta en tu oficina.",
    createPin: "Crea tu PIN",
    createPinHint: "Escoge 4 números que vas a recordar",
    confirmPin: "Escríbelo otra vez",
    pinMismatch: "No coincide — intenta otra vez",
    setupClosed: "La creación de PIN no está abierta. Pregunta en tu oficina.",
    signedOut: "Sesión cerrada. Empieza otra vez.",
    whatDidYouUse: "¿Qué usaste?",
    noEquipment: "No hay equipo todavía.",
    howDidYouLeaveIt: "¿Cómo lo dejaste?",
    good: "Bien",
    damaged: "Dañado o no funciona",
    lost: "Perdido",
    takePicture: "TOMAR FOTO",
    photoRequired: "Toma al menos 1 foto",
    photoCount: (n: number) => `${n}/3 fotos`,
    photoTooBig: "Esa foto es muy grande (máximo 8MB).",
    notesPlaceholder: "Notas / Comentarios",
    send: "ENVIAR",
    sending: "Enviando…",
    done: "¡Listo! Gracias",
    vehicle: "Vehículo",
    mileageQuestion: "¿Millaje?",
    mileageHint: "El número en el tablero",
    next: "SIGUIENTE",
    lastMileage: (n: string) => `Última vez: ${n}`,
    lowerCheck: (last: string) => `¿Seguro? La última lectura fue ${last}`,
    yesRight: "Sí, está bien",
    fixIt: "Corregir",
  },
} as const;

export function equipmentCheckStrings(lang: TeamHubLang) {
  return EQUIPMENT_CHECK_STRINGS[lang];
}

// "Add to Home Screen" steps — shown to managers in "Set up a tablet" (both
// languages, all devices) and on the tablet itself as a dismissible banner
// (device language, that device's steps only).
export type InstallPlatform = "ios" | "android" | "other";

export const INSTALL_STEPS: Record<TeamHubLang, { title: string; all: string[]; byPlatform: Record<InstallPlatform, string[]>; gotIt: string }> = {
  en: {
    title: "Add this app to the Home Screen",
    all: ["1. Scan with the tablet camera.", "2. Tap Share (iPad) or ⋮ (Android).", "3. Tap Add to Home Screen."],
    byPlatform: {
      ios: ["1. Tap Share (the square with an arrow).", "2. Tap Add to Home Screen."],
      android: ["1. Tap ⋮ (top right).", "2. Tap Add to Home screen."],
      other: ["1. Tap Share (iPad) or ⋮ (Android).", "2. Tap Add to Home Screen."],
    },
    gotIt: "Got it",
  },
  es: {
    title: "Agrega esta app a la pantalla de inicio",
    all: ["1. Escanea con la cámara de la tableta.", "2. Toca Compartir (iPad) o ⋮ (Android).", "3. Toca Agregar a inicio."],
    byPlatform: {
      ios: ["1. Toca Compartir (el cuadro con la flecha).", "2. Toca Agregar a inicio."],
      android: ["1. Toca ⋮ (arriba a la derecha).", "2. Toca Agregar a la pantalla principal."],
      other: ["1. Toca Compartir (iPad) o ⋮ (Android).", "2. Toca Agregar a inicio."],
    },
    gotIt: "Entendido",
  },
};
