export const accounts = [
  {
    id: 1,
    name: "AIM - Aviation Institute of Maintenance",
    address: "Hasbrouck Heights, NJ",
    manager: "Andrés",
    subcontractorId: 1,
    subcontractor: "Fernando",

    cleaningWorldMonthlyBilling: 7500,
    subcontractorMonthlyPay: 5200,
    grossMonthlyMargin: 2300,
    monthlyRevenue: 7500,

    serviceFrequency: "5x per week",
    healthScore: 8,

    accountStatus: "Active",
    accountHealth: "Needs Attention",
    status: "Needs Attention",

    lastVisit: "2026-06-01",
    openComplaints: 1,

    hasKey: true,
    keyNotes: "Office key on file.",
    hasAlarm: true,
    alarmCode: "1234",
    alarmNotes: "Disarm upon entry and re-arm before leaving.",
  },
  {
    id: 2,
    name: "Ferragamo",
    address: "New Jersey",
    manager: "Greg",
    subcontractorId: 2,
    subcontractor: "Edgar",

    cleaningWorldMonthlyBilling: 6200,
    subcontractorMonthlyPay: 4300,
    grossMonthlyMargin: 1900,
    monthlyRevenue: 6200,

    serviceFrequency: "5x per week",
    healthScore: 9,

    accountStatus: "Active",
    accountHealth: "Good",
    status: "Good",

    lastVisit: "2026-06-02",
    openComplaints: 0,

    hasKey: true,
    keyNotes: "Key access available.",
    hasAlarm: true,
    alarmCode: "5678",
    alarmNotes: "Alarm must be disarmed before cleaning starts.",
  },
  {
    id: 3,
    name: "Lehmann Pools",
    address: "New Jersey",
    manager: "Drew",
    subcontractorId: 3,
    subcontractor: "Juana",

    cleaningWorldMonthlyBilling: 4200,
    subcontractorMonthlyPay: 3000,
    grossMonthlyMargin: 1200,
    monthlyRevenue: 4200,

    serviceFrequency: "3x per week",
    healthScore: 9,

    accountStatus: "Active",
    accountHealth: "Good",
    status: "Good",

    lastVisit: "2026-06-03",
    openComplaints: 0,

    hasKey: false,
    keyNotes: "Customer provides access during service hours.",
    hasAlarm: false,
    alarmCode: "",
    alarmNotes: "No alarm information on file.",
  },
  {
    id: 4,
    name: "4Wall Entertainment",
    address: "New Jersey",
    manager: "Andrés",
    subcontractorId: 4,
    subcontractor: "Vicky",

    cleaningWorldMonthlyBilling: 5100,
    subcontractorMonthlyPay: 3600,
    grossMonthlyMargin: 1500,
    monthlyRevenue: 5100,

    serviceFrequency: "5x per week",
    healthScore: 8,

    accountStatus: "Active",
    accountHealth: "Monitor",
    status: "Monitor",

    lastVisit: "2026-05-30",
    openComplaints: 1,

    hasKey: true,
    keyNotes: "Rear entrance key on file.",
    hasAlarm: true,
    alarmCode: "2468",
    alarmNotes: "Use rear entrance and disarm immediately.",
  },
  {
    id: 5,
    name: "Independent Chemical",
    address: "New Jersey",
    manager: "Greg",
    subcontractorId: 2,
    subcontractor: "Edgar",

    cleaningWorldMonthlyBilling: 3900,
    subcontractorMonthlyPay: 2700,
    grossMonthlyMargin: 1200,
    monthlyRevenue: 3900,

    serviceFrequency: "2x per week",
    healthScore: 10,

    accountStatus: "Active",
    accountHealth: "Good",
    status: "Good",

    lastVisit: "2026-06-01",
    openComplaints: 0,

    hasKey: false,
    keyNotes: "Access provided by customer.",
    hasAlarm: false,
    alarmCode: "",
    alarmNotes: "No alarm information on file.",
  },
];

export const subcontractors = [
  {
    id: 1,
    name: "Fernando",
    contactName: "Fernando",
    companyName: "Fernando Cleaning Services",
    address: "Not entered",
    phone: "Not entered",
    email: "Not entered",
    areasServiced: "North Jersey",
    servicesProvided: "Janitorial cleaning",
    employeeCapacity: 4,
    status: "Active",
    insuranceDocumentName: "No document uploaded",
    insuranceExpirationDate: "Not entered",
    accountsAssigned: ["AIM - Aviation Institute of Maintenance"],
    monthlyPayTotal: 5200,
    complaintsCount: 1,
    averageHealthScore: 8,
    notes:
      "Handles AIM. Needs follow-up on restroom and hallway detail cleaning.",
  },
  {
    id: 2,
    name: "Edgar",
    contactName: "Edgar",
    companyName: "Edgar Cleaning Services",
    address: "Not entered",
    phone: "Not entered",
    email: "Not entered",
    areasServiced: "New Jersey",
    servicesProvided: "Janitorial cleaning, floor care",
    employeeCapacity: 6,
    status: "Active",
    insuranceDocumentName: "No document uploaded",
    insuranceExpirationDate: "Not entered",
    accountsAssigned: ["Ferragamo", "Independent Chemical"],
    monthlyPayTotal: 7000,
    complaintsCount: 0,
    averageHealthScore: 9.5,
    notes: "Good performance overall.",
  },
  {
    id: 3,
    name: "Juana",
    contactName: "Juana",
    companyName: "Juana Cleaning Services",
    address: "Not entered",
    phone: "Not entered",
    email: "Not entered",
    areasServiced: "New Jersey",
    servicesProvided: "Janitorial cleaning",
    employeeCapacity: 3,
    status: "Active",
    insuranceDocumentName: "No document uploaded",
    insuranceExpirationDate: "Not entered",
    accountsAssigned: ["Lehmann Pools"],
    monthlyPayTotal: 3000,
    complaintsCount: 0,
    averageHealthScore: 9,
    notes: "Good account condition.",
  },
  {
    id: 4,
    name: "Vicky",
    contactName: "Vicky",
    companyName: "Vicky Cleaning Services",
    address: "Not entered",
    phone: "Not entered",
    email: "Not entered",
    areasServiced: "New Jersey",
    servicesProvided: "Janitorial cleaning",
    employeeCapacity: 4,
    status: "Active",
    insuranceDocumentName: "No document uploaded",
    insuranceExpirationDate: "Not entered",
    accountsAssigned: ["4Wall Entertainment"],
    monthlyPayTotal: 3600,
    complaintsCount: 1,
    averageHealthScore: 8,
    notes: "Needs monitoring due to detail cleaning complaint.",
  },
];

export const visits = [
  {
    id: 1,
    accountId: 1,
    accountName: "AIM - Aviation Institute of Maintenance",
    manager: "Andrés",
    date: "2026-06-01",
    conditionScore: 7,
    notes:
      "Restrooms were acceptable, but hallway trash needed more attention. Follow-up required with subcontractor.",
    followUpNeeded: true,
  },
  {
    id: 2,
    accountId: 2,
    accountName: "Ferragamo",
    manager: "Greg",
    date: "2026-06-02",
    conditionScore: 9,
    notes: "Account looked good. No major issues reported during visit.",
    followUpNeeded: false,
  },
  {
    id: 3,
    accountId: 3,
    accountName: "Lehmann Pools",
    manager: "Drew",
    date: "2026-06-03",
    conditionScore: 9,
    notes: "Good overall condition. Customer was satisfied.",
    followUpNeeded: false,
  },
  {
    id: 4,
    accountId: 4,
    accountName: "4Wall Entertainment",
    manager: "Andrés",
    date: "2026-05-30",
    conditionScore: 8,
    notes:
      "Service was mostly good, but some detail cleaning was missed near production area.",
    followUpNeeded: true,
  },
];

export const complaints = [
  {
    id: 1,
    accountId: 1,
    accountName: "AIM - Aviation Institute of Maintenance",
    dateOpened: "2026-06-01",
    issue: "Trash and restroom detail cleaning missed.",
    status: "Open",
    assignedTo: "Fernando",
    resolutionNotes: "",
  },
  {
    id: 2,
    accountId: 4,
    accountName: "4Wall Entertainment",
    dateOpened: "2026-05-30",
    issue: "Detail cleaning missed near production area.",
    status: "In Progress",
    assignedTo: "Vicky",
    resolutionNotes: "Manager spoke with subcontractor. Follow-up visit scheduled.",
  },
  {
    id: 3,
    accountId: 2,
    accountName: "Ferragamo",
    dateOpened: "2026-05-25",
    issue: "Request for additional floor care service.",
    status: "Closed",
    assignedTo: "Greg",
    resolutionNotes: "Estimate sent to customer.",
  },
];

export const followups = [
  {
    id: 1,
    accountId: 1,
    accountName: "AIM - Aviation Institute of Maintenance",
    dueDate: "2026-06-05",
    assignedTo: "Andrés",
    note: "Confirm restroom and hallway trash issues were corrected.",
    status: "Pending",
  },
  {
    id: 2,
    accountId: 4,
    accountName: "4Wall Entertainment",
    dueDate: "2026-06-06",
    assignedTo: "Andrés",
    note: "Revisit production area and confirm detail cleaning improvement.",
    status: "Pending",
  },
];

export const sales = [
  {
    id: 1,
    accountId: 1,
    accountName: "AIM - Aviation Institute of Maintenance",
    service: "Weekend Janitorial Service",
    soldBy: "Andrés",
    amount: 1800,
    commissionPercent: 5,
    commissionAmount: 90,
    status: "Pending",
    date: "2026-06-01",
  },
  {
    id: 2,
    accountId: 2,
    accountName: "Ferragamo",
    service: "Floor Strip & Wax",
    soldBy: "Greg",
    amount: 3200,
    commissionPercent: 5,
    commissionAmount: 160,
    status: "Approved",
    date: "2026-06-02",
  },
  {
    id: 3,
    accountId: 3,
    accountName: "Lehmann Pools",
    service: "Carpet Cleaning",
    soldBy: "Drew",
    amount: 950,
    commissionPercent: 5,
    commissionAmount: 47.5,
    status: "Completed",
    date: "2026-06-03",
  },
];

export const accountUpdates = [
  {
    id: 1,
    accountId: 1,
    accountName: "AIM - Aviation Institute of Maintenance",
    date: "2026-06-01",
    updateType: "Service Issue",
    title: "Restroom and hallway trash issue reported",
    details:
      "Customer reported missed trash and restroom detail cleaning. Follow-up required with subcontractor.",
    createdBy: "Andrés",
    notifyByEmail: true,
    status: "Open",
  },
  {
    id: 2,
    accountId: 2,
    accountName: "Ferragamo",
    date: "2026-06-02",
    updateType: "Extra Service",
    title: "Floor strip and wax estimate sent",
    details:
      "Estimate was sent for floor strip and wax service. Waiting for customer approval.",
    createdBy: "Greg",
    notifyByEmail: false,
    status: "Pending",
  },
  {
    id: 3,
    accountId: 4,
    accountName: "4Wall Entertainment",
    date: "2026-05-30",
    updateType: "Account Note",
    title: "Production area detail cleaning needs monitoring",
    details:
      "Manager noticed missed detail cleaning near production area. Subcontractor was contacted and follow-up visit is scheduled.",
    createdBy: "Andrés",
    notifyByEmail: true,
    status: "In Progress",
  },
];