// EN/ES words for the crew-facing Crew Link screens (docs/crew-link-spec.md).
// Kept short on purpose: crews are on phones, often Spanish-speaking, and not
// tech-savvy — few words, big buttons. Language follows the phone, with an
// always-visible English/Español switch; the choice is remembered per phone.
import type { TeamHubLang } from "@/app/team-hub/teamHubStrings";

export const CREW_LINK_STRINGS = {
  en: {
    appName: "Crew Link",
    defaultTitle: "Crew Link",
    loading: "Loading…",
    unavailableTitle: "This link is not active",
    unavailableBody: "Ask your office for a new link.",
    somethingWrong: "Something went wrong. Try again.",
    noSignal: "No signal. Try again.",
    whatsYourName: "What's your name?",
    next: "Next",
    hi: (name: string) => `Hi, ${name}`,
    notYou: "Not you?",
    back: "Back",
    checklist: "Checklist",
    supplies: "Supplies",
    problem: "Problem",
    nothingHere: "Nothing here yet. Ask your office.",
    progress: (done: number, total: number) => `${done} of ${total} done`,
    noteOptional: "Note (optional)",
    send: "Send",
    sending: "Sending…",
    sent: "Sent!",
    backToStart: "Back to start",
    sendOrder: "Send order",
    otherSuppliesLabel: "Other supplies not on the list",
    otherSuppliesPlaceholder: "Item and how many cases, e.g. Degreaser, 2 cases",
    noteForOffice: "Note for the office (optional)",
    pickSupplies: "Tap + on an item, or write other supplies.",
    recentOrders: "Your recent orders",
    otherPrefix: "Other",
    orderStatus: { new: "Sent", ordered: "Ordered", delivered: "Delivered", cancelled: "Cancelled" },
    whatsWrong: "What's wrong?",
    takePhoto: "Take photo",
    photoCount: (n: number, max: number) => `${n} of ${max} photos`,
    tooManyPhotos: "Up to 5 photos.",
    photoTooBig: "That photo is too big.",
    noteRequired: "Write what it is (required)",
  },
  es: {
    appName: "Crew Link",
    defaultTitle: "Crew Link",
    loading: "Cargando…",
    unavailableTitle: "Este enlace no está activo",
    unavailableBody: "Pide un enlace nuevo en tu oficina.",
    somethingWrong: "Algo salió mal. Intenta de nuevo.",
    noSignal: "Sin señal. Intenta de nuevo.",
    whatsYourName: "¿Cómo te llamas?",
    next: "Siguiente",
    hi: (name: string) => `Hola, ${name}`,
    notYou: "¿No eres tú?",
    back: "Atrás",
    checklist: "Lista",
    supplies: "Suministros",
    problem: "Problema",
    nothingHere: "Nada aquí todavía. Pregunta en tu oficina.",
    progress: (done: number, total: number) => `${done} de ${total} hechos`,
    noteOptional: "Nota (opcional)",
    send: "Enviar",
    sending: "Enviando…",
    sent: "¡Enviado!",
    backToStart: "Volver al inicio",
    sendOrder: "Enviar pedido",
    otherSuppliesLabel: "Otros suministros que no están en la lista",
    otherSuppliesPlaceholder: "Artículo y cuántas cajas, p. ej. Desengrasante, 2 cajas",
    noteForOffice: "Nota para la oficina (opcional)",
    pickSupplies: "Toca + en un artículo, o escribe otros suministros.",
    recentOrders: "Tus pedidos recientes",
    otherPrefix: "Otros",
    orderStatus: { new: "Enviado", ordered: "Pedido", delivered: "Entregado", cancelled: "Cancelado" },
    whatsWrong: "¿Qué pasa?",
    takePhoto: "Tomar foto",
    photoCount: (n: number, max: number) => `${n} de ${max} fotos`,
    tooManyPhotos: "Hasta 5 fotos.",
    photoTooBig: "Esa foto es muy grande.",
    noteRequired: "Escribe qué es (obligatorio)",
  },
} as const;

export type CrewLinkStrings = (typeof CREW_LINK_STRINGS)[TeamHubLang];

export function crewLinkStrings(lang: TeamHubLang): CrewLinkStrings {
  return CREW_LINK_STRINGS[lang];
}
